services:
  nodejs-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nodejs-container
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - NODE_ENV=production
    depends_on:
      fastapi-service:
        condition: service_healthy

  fastapi-service:
    build:
      context: ./model
      dockerfile: Dockerfile
    container_name: fastapi-container
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - FASTAPI_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8000/health"]
      interval: 180s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
