apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: fastapi-service
  name: fastapi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fastapi-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: fastapi-service
    spec:
      containers:
        - env:
            - name: FASTAPI_ENV
              value: production
          image: fastapi:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://0.0.0.0:8000/health
            failureThreshold: 5
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
          name: fastapi-container
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
