apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: nodejs-service
  name: nodejs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: nodejs-service
    spec:
      containers:
        - args:
            - wait-for-it
            - mysql-service:3306
            - --
            - npm
            - start
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_NAME
              value: db
            - name: DB_PASSWORD
              value: "1234"
            - name: DB_USER
              value: admin
          image: coinguesser-back-fastapi-service:latest
          name: nodejs-container
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
