# .github/workflows/ci.yml
name: CI for Node.js and FastAPI

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      #  Build and run FastAPI service
      - name: Build FastAPI service
        run: docker build -t fastapi-service ./model

      - name: Run FastAPI service
        run: |
          docker run -d --name fastapi-container -p 8000:8000 -v ${{ github.workspace }}/test:/app/test fastapi-service

      #  Wait for FastAPI service to be ready (Optional)
      - name: Wait for FastAPI service to be ready
        run: sleep 10 # 필요한 경우 이 값을 조정하여 서비스 시작 시간 고려

      #  Run FastAPI tests
      - name: Run FastAPI tests
        run: docker exec fastapi-container pytest test/

      - name: Print success message
        if: success()
        run: echo "All tests passed successfully!"

      #  Tear down Node.js and FastAPI containers
      - name: Stop and remove Node.js and FastAPI containers
        if: always()
        run: |
          docker stop fastapi-container
          docker rm fastapi-container
